### ISSUE TITLE
How to group certain features by using tags?

### ISSUE THREAD

**Issue by huiyangns** [olexale/bdd_widget_test#34] opened 2022-09-26 06:35 UTC
For integration test running in a browser, is there any configuration to set tags and using them to group feature files?

It seems that unlike flutter test command, flutter drive command does not provide --tag option

Another question is when a feature file fails, how to capture the screenshot at fail time?

Thanks

**Comment by olexale** [comment] 2022-09-26 08:44
`flutter driver` does not support tags. I'd recommend updating the test suite to the `integration_test` framework, it's been there for quite a long time. If, for any reason, you can not do that - take an eye on [this issue](https://github.com/flutter/flutter/issues/25141). Once it is solved, tags will appear automatically.

`bdd_widget_test` doesn't add any functionality by itself. if you need to capture screenshots - you need to implement this. I see two options from the top of my head:
1. You may use the `AFTER` section for capturing the screenshot. Steps from this section will always be executed, so you'd need to define what is "fail time" in your steps.
2. You may wrap common steps (like `iWait`, `iTap`, etc.) implementations in `try..catch` blocks and make screenshots there. A bit more boilerplate, but at the same time, you'll get more control.

Additionally, I'd recommend giving it a try without screenshots. On a scale they will significantly slow down testing execution. You will learn how to debug tests quite soon, so try to keep your test suit rapid.

**Comment by huiyangns** [comment] 2022-09-26 18:26
Hi Olexale,

Thanks for replying. I have updated my test suite to integration_test framework. But according to the official document, when 
running integration_test in the browser, we have to use  flutter drive to do that.
So it seems that we lose the ability to group feature files by tags under that situation.

Is there any work round to deal with this issue except waiting adding tags support to flutter drive command?

**Comment by olexale** [comment] 2022-09-27 05:45
Hey @huiyangns,

With `flutter test`, it's possible to filter which tests to run by test name (`--name` parameter). I'd investigate whether there is something similar exists with `flutter driver`.

If not - probably not the best solution, but you may just remove tests that are not needed before running all tests. You always will be able to generate them back from feature files.

**Comment by olexale** [comment] 2022-10-11 12:19
I'm closing this issue as it is not a bug or feature request. Feel free to re-open it or create a new one if needed.

**Closed by olexale** 2022-10-11 12:19 UTC
